In [6]:
import pandas as pd

In [7]:
import numpy as np

In [14]:
data  = pd.DataFrame(np.random.randn(20, 4), index = pd.date_range('1/1/2021', periods=20), columns = ['A', 'B','C','D'])

In [15]:
data

                   A         B         C         D
2021-01-01  0.244911  0.035925  0.294991  0.049904
2021-01-02 -0.228483  0.540330 -0.967865 -2.050295
2021-01-03 -1.258715  1.246531  1.094063 -0.240334
2021-01-04 -0.736650 -2.113045 -0.243316  0.830692
2021-01-05  0.423591 -0.270029 -0.202619 -0.630181
2021-01-06  0.482220  0.689408 -0.219438 -0.340103
2021-01-07  0.282525 -0.125602  1.452346  1.051336
2021-01-08 -0.960457  2.149514 -1.680957  0.650583
2021-01-09 -0.429917  1.426590 -1.472786 -0.591363
2021-01-10  0.568744  0.477817 -0.123891  0.225543
2021-01-11  0.673611  0.140877 -0.979419  0.080163
2021-01-12  0.136857 -1.161609 -0.583560 -0.302725
2021-01-13  0.007079 -0.568466  0.170747 -0.325437
2021-01-14 -0.490556 -0.453064 -0.448031  0.570579
2021-01-15  1.207016 -0.697743  2.184888 -1.686873
2021-01-16 -0.162560 -0.299554  0.649365  0.198924
2021-01-17  0.242298  0.340025 -0.048445  0.522669
2021-01-18 -0.269429  0.344080 -1.828401  0.614115
2021-01-19  1.249345  2.735623  0.256311  0.757615
2021-01-20  1.744166  0.320146  0.488374 -0.424945

In [21]:
r = data.rolling(window=3, min_periods=1)

In [22]:
r.aggregate(np.sum)

                   A         B         C         D
2021-01-01  0.244911  0.035925  0.294991  0.049904
2021-01-02  0.016428  0.576255 -0.672874 -2.000391
2021-01-03 -1.242286  1.822786  0.421190 -2.240725
2021-01-04 -2.223848 -0.326184 -0.117117 -1.459936
2021-01-05 -1.571774 -1.136543  0.648128 -0.039823
2021-01-06  0.169160 -1.693666 -0.665374 -0.139592
2021-01-07  1.188335  0.293776  1.030288  0.081052
2021-01-08 -0.195712  2.713319 -0.448049  1.361816
2021-01-09 -1.107849  3.450502 -1.701397  1.110555
2021-01-10 -0.821630  4.053921 -3.277634  0.284762
2021-01-11  0.812438  2.045284 -2.576097 -0.285657
2021-01-12  1.379212 -0.542916 -1.686871  0.002981
2021-01-13  0.817548 -1.589199 -1.392232 -0.547998
2021-01-14 -0.346619 -2.183139 -0.860844 -0.057583
2021-01-15  0.723539 -1.719273  1.907603 -1.441731
2021-01-16  0.553900 -1.450361  2.386222 -0.917370
2021-01-17  1.286753 -0.657272  2.785808 -0.965280
2021-01-18 -0.189691  0.384551 -1.227481  1.335709
2021-01-19  1.222214  3.419728 -1.620536  1.894400
2021-01-20  2.724081  3.399849 -1.083717  0.946785

In [23]:
r['A'].aggregate(np.sum)

2021-01-01    0.244911
2021-01-02    0.016428
2021-01-03   -1.242286
2021-01-04   -2.223848
2021-01-05   -1.571774
2021-01-06    0.169160
2021-01-07    1.188335
2021-01-08   -0.195712
2021-01-09   -1.107849
2021-01-10   -0.821630
2021-01-11    0.812438
2021-01-12    1.379212
2021-01-13    0.817548
2021-01-14   -0.346619
2021-01-15    0.723539
2021-01-16    0.553900
2021-01-17    1.286753
2021-01-18   -0.189691
2021-01-19    1.222214
2021-01-20    2.724081
Freq: D, Name: A, dtype: float64

In [24]:
r[['A','B']].aggregate(np.sum)

                   A         B
2021-01-01  0.244911  0.035925
2021-01-02  0.016428  0.576255
2021-01-03 -1.242286  1.822786
2021-01-04 -2.223848 -0.326184
2021-01-05 -1.571774 -1.136543
2021-01-06  0.169160 -1.693666
2021-01-07  1.188335  0.293776
2021-01-08 -0.195712  2.713319
2021-01-09 -1.107849  3.450502
2021-01-10 -0.821630  4.053921
2021-01-11  0.812438  2.045284
2021-01-12  1.379212 -0.542916
2021-01-13  0.817548 -1.589199
2021-01-14 -0.346619 -2.183139
2021-01-15  0.723539 -1.719273
2021-01-16  0.553900 -1.450361
2021-01-17  1.286753 -0.657272
2021-01-18 -0.189691  0.384551
2021-01-19  1.222214  3.419728
2021-01-20  2.724081  3.399849